{"name": "test_mul_004", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <test_case_005.Test_Credence_005 object at 0x0000016239F80750>\n\n    def test_mul_004(self):\n        a = 3\n        b = 7\n        mul = a * b\n        print(\"Mul of a and b is :\" + str(mul))\n        if mul == 10:\n            assert True\n        else:\n>           assert False\nE           assert False\n\ntest_case_005.py:11: AssertionError"}, "start": 1690661985766, "stop": 1690661985766, "uuid": "27264afb-f9aa-49bd-a074-4b4cbfe0718e", "historyId": "f87ced7662c25b3c732ac3cfc03d7974", "testCaseId": "f87ced7662c25b3c732ac3cfc03d7974", "fullName": "test_case_005.Test_Credence_005#test_mul_004", "labels": [{"name": "suite", "value": "test_case_005"}, {"name": "subSuite", "value": "Test_Credence_005"}, {"name": "host", "value": "Renu"}, {"name": "thread", "value": "54704-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case_005"}]}